# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('locomocao', models.CharField(max_length=50)),
                ('respiracao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomehabitat', models.CharField(max_length=50)),
                ('detalhe', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReproducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomereproducao', models.CharField(max_length=50)),
                ('detalhe', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Anfibio',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registroanimal.Animal')),
                ('cauda', models.CharField(max_length=10)),
            ],
            bases=('registroanimal.animal',),
        ),
        migrations.CreateModel(
            name='Ave',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registroanimal.Animal')),
                ('voa', models.CharField(max_length=10)),
            ],
            bases=('registroanimal.animal',),
        ),
        migrations.CreateModel(
            name='Mamifero',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registroanimal.Animal')),
                ('pelo', models.CharField(max_length=10)),
            ],
            bases=('registroanimal.animal',),
        ),
        migrations.CreateModel(
            name='Peixe',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registroanimal.Animal')),
                ('nadadeira', models.CharField(max_length=50)),
                ('escama', models.CharField(max_length=10)),
            ],
            bases=('registroanimal.animal',),
        ),
        migrations.CreateModel(
            name='Repteis',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registroanimal.Animal')),
                ('classe', models.CharField(max_length=50)),
            ],
            bases=('registroanimal.animal',),
        ),
        migrations.AddField(
            model_name='animal',
            name='tipohabitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroanimal.TipoHabitat'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tiporeproducao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroanimal.TipoReproducao'),
        ),
    ]
