# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroanimal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfibio',
            name='nomeanfibio',
            field=models.CharField(default='nomeanfibio', max_length=200),
        ),
        migrations.AddField(
            model_name='ave',
            name='nomeave',
            field=models.CharField(default='nomeave', max_length=200),
        ),
        migrations.AddField(
            model_name='mamifero',
            name='nomemamifero',
            field=models.CharField(default='nomemamifero', max_length=200),
        ),
        migrations.AddField(
            model_name='peixe',
            name='nomepeixe',
            field=models.CharField(default='nomepeixe', max_length=200),
        ),
        migrations.AddField(
            model_name='repteis',
            name='nomerepteis',
            field=models.CharField(default='nomerepteis', max_length=200),
        ),
    ]
