# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroanimal', '0002_auto_20170408_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipohabitat',
            name='detalhe',
        ),
    ]
